import Head from 'next/head';
import styles from '../../styles/HomeAdmin.module.css';
import { useSession } from 'next-auth/react';
import React, { useState } from 'react';
import { useRouter } from 'next/router';
import Loading from '../../components/Loading';
import { Button, ButtonGroup } from '@mui/material';

export enum PageOption {
	orders = 'order',
	form = 'form',
	users = 'users',
}

const Home = () => {
	const { data: session, status } = useSession();
	const [pageOption, setPageOption] = useState<PageOption>(PageOption.orders);

	if (status === 'loading') return <Loading />;

	if (status === 'authenticated' && session.user?.admin) {
		return (
			<>
				<div className={styles.container}>
					<Head>
						<title>Admin Page</title>
						<meta
							name='description'
							content='Generated by create next app'
						/>
						<link rel='icon' href='/favicon.ico' />
					</Head>

					<main className={styles.main}>
						<ButtonGroup
							size='large'
							aria-label='large button group'>
							<Button
								style={
									pageOption === PageOption.orders
										? {
												backgroundColor: '#1876D2',
												color: 'white',
										  }
										: {}
								}
								onClick={() =>
									setPageOption(PageOption.orders)
								}>
								Orders
							</Button>
							<Button
								onClick={() => setPageOption(PageOption.form)}
								style={
									pageOption === PageOption.form
										? {
												backgroundColor: '#1876D2',
												color: 'white',
										  }
										: {}
								}>
								Form
							</Button>
							<Button
								onClick={() => setPageOption(PageOption.users)}
								style={
									pageOption === PageOption.users
										? {
												backgroundColor: '#1876D2',
												color: 'white',
										  }
										: {}
								}>
								Users
							</Button>
						</ButtonGroup>
						{}
					</main>

					<footer className={styles.footer}>
						Politechnika Wrocławska
					</footer>
				</div>
			</>
		);
	}
	return (
		<>
			<div className={styles.container}>
				<main className={styles.main}>
					<h1>This is admin page please SIGNIN to access</h1>
				</main>
				<footer className={styles.footer}>
					Politechnika Wrocławska
				</footer>
			</div>
		</>
	);
};

export default Home;
