import Head from 'next/head';
import Nav from '../components/Navbar';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSession } from 'next-auth/react';
import React from 'react';

const Home = () => {
	const { data } = useSession();

	return (
		<div className={styles.container}>
			<Nav />
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome{' '}
					<a href='#'>
						{data?.user?.name + ' ' + data?.user?.surname}
					</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>
			</main>

			<footer className={styles.footer}>Politechnika Wrocławska</footer>
		</div>
	);
};

export default Home;
